PR: Rédaction du README
cgq-qgc/Hello pull request #1
Opened 2018-11-15 19:36 UTC by jnsebgosselin

2018-11-15 20:44 UTC, FHuchet commented
Le texte est concis et clair. On pourra le compléter par la suite au besoin.

Peut-être ajouter ou avoir un courriel "RNCAN" dans les contacts au lieu des deux adresses "INRS" ? Mais ce n'est pas bien grave...

2018-11-15 20:48 UTC, FHuchet commented
Il manque juste un "espace" avant les ":" et le "?".

2018-11-15 22:48 UTC, jnsebgosselin commented
@FHuchet et @haroldvigneault 
J'ai pas mal fini ce que je voulais faire pour l'instant. Je propose de merger le tout directement dans la branche `Master` une fois que vous aurez terminer d'apporter vos corrections.

Ensuite, on devrait faire valider le tout par Pascale de la CGC et Jean-Daniel de l'INRS et on apportera leur modifications dans une autre PR.

Qu'est-ce que vous en pensez?

2018-11-16 12:20 UTC, jnsebgosselin commented
> Peut-être ajouter ou avoir un courriel "RNCAN" dans les contacts au lieu des deux adresses "INRS" ? Mais ce n'est pas bien grave..

@haroldvigneault est-ce que tu pourrais mettre ton adresse NRCAN au lieu de INRS? Je trouve que c'est une bonne idée.

2018-11-16 12:21 UTC, jnsebgosselin commented
> C'est super le code de conduite! L’INRS et/ou la CGC ont des codes de conduite je me demande si nous y sommes assujetti.

Est-ce que l'on devrais utiliser un de ces codes à la place? Est-ce qu'ils sont adaptés à un groupe comme celui-ci?

2018-11-16 13:36 UTC, jnsebgosselin commented
J'ai repensé à ca, pour éviter des problèmes, il faudrait montrer ces propositions de changements à Jean-Daniel, Pascal et J-F avant de merger.

2018-11-16 14:12 UTC, FHuchet commented
J'ai fait quelques modifications ce matin dans les deux documents (surtout sur la forme). Le fond me paraît vraiment bien.

2018-11-16 14:37 UTC, jnsebgosselin reviewed
Désolé, ceci était un test pour voir si je pouvais approuver les changements, mais comme je suis l'auteur du PR, je ne peux pas évidemment...

2018-11-16 15:17 UTC, jnsebgosselin commented
@FHuchet je trouve que tes modifications sur le code de conduite sont très pertinentes... je me demande si ça ne vaudrait pas la peine de proposer cela "upstream"... Je peux t'aider à le faire si jamais ça t'intéresse.

2018-11-16 22:53 UTC, FHuchet requested changes
Je me permets de tester le processus de révision sur GitHub.

Il y a juste l'adresse d'Harold à l'INRS, en a-t-il une à la CGC ?

2018-11-17 15:11 UTC, jnsebgosselin commented
>Je me permets de tester le processus de révision sur GitHub.

> Il y a juste l'adresse d'Harold à l'INRS, en a-t-il une à la CGC ?

@haroldvigneault me disait que ce ne serait pas pratique de mettre son adresse de la CGC, parce qu'il n'a que de courts contrats et qu'il ne s'en sert pas beaucoup.

2018-11-19 13:43 UTC, FHuchet approved these changes

2018-11-23 21:55 UTC, jnsebgosselin commented
![image](https://user-images.githubusercontent.com/10170372/48961189-931e9300-ef40-11e8-8a9c-1f5125c87917.png)

2018-11-26 13:49 UTC, FHuchet commented
Merci pour les corrections de Pascale Côté.

2018-11-26 13:51 UTC, FHuchet approved these changes

2018-11-26 21:08 UTC, haroldvigneault approved these changes

2018-11-27 19:47 UTC, merged